/**
 * schema.js — Drizzle ORM Schema Definitions
 *
 * Single source of truth for the database structure.
 * Drizzle Kit reads this file to generate SQL migration files.
 *
 * Tables:
 *   1. users                — all platform users (EMP, RM, APE, CFO)
 *   2. reimbursements       — expense reimbursement requests filed by employees
 *   3. employeeAssignments  — maps each employee to their reporting manager (RM)
 */

const {
  pgTable,
  serial,
  uuid,
  varchar,
  text,
  decimal,
  boolean,
  timestamp,
} = require('drizzle-orm/pg-core');

// ─────────────────────────────────────────────────────────────────────────────
// TABLE 1: users
// ─────────────────────────────────────────────────────────────────────────────
// Central identity table. Every person who interacts with the system has
// exactly one row here. The `userId` (UUID) is the only identifier exposed
// via API — the internal `id` (SERIAL) is never sent to clients.
// ─────────────────────────────────────────────────────────────────────────────
const users = pgTable('users', {
  /** Internal auto-increment PK; never exposed via API. */
  id: serial('id').primaryKey(),

  /** External API identifier — a UUID v4 auto-generated by PostgreSQL. */
  userId: uuid('user_id').defaultRandom().notNull().unique(),

  /** Full display name (e.g. "Rahul Sharma"). */
  name: varchar('name', { length: 255 }).notNull(),

  /** Unique login identifier; also used for email notifications. */
  email: varchar('email', { length: 255 }).notNull().unique(),

  /** bcrypt hash — plain-text passwords are NEVER stored. */
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),

  /**
   * User role in the organization.
   * Allowed values: 'EMP' | 'RM' | 'APE' | 'CFO'
   *   EMP = Employee (files reimbursement requests)
   *   RM  = Reporting Manager (first-level approver)
   *   APE = Accounts Payable Executive (second-level approver)
   *   CFO = Chief Financial Officer (final approver)
   */
  role: varchar('role', { length: 10 }).notNull(),

  /** Row creation timestamp; useful for audit trails. */
  createdAt: timestamp('created_at').defaultNow(),
});

// ─────────────────────────────────────────────────────────────────────────────
// TABLE 2: reimbursements
// ─────────────────────────────────────────────────────────────────────────────
// Each row is a single reimbursement request created by an employee.
// The approval pipeline is tracked via three boolean flags:
//   rmApproved → apeApproved → cfoApproved
// Once all three are TRUE the overall status flips to 'APPROVED'.
// If any approver rejects, the status becomes 'REJECTED'.
// ─────────────────────────────────────────────────────────────────────────────
const reimbursements = pgTable('reimbursements', {
  /** Internal PK, never exposed. */
  id: serial('id').primaryKey(),

  /** Public UUID used in API routes (e.g. GET /reimbursements/:id). */
  reimbursementId: uuid('reimbursement_id').defaultRandom().notNull().unique(),

  /**
   * FK → users.user_id — the employee who filed this request.
   * CASCADE: if the employee is deleted, their requests are removed too.
   */
  userId: uuid('user_id')
    .notNull()
    .references(() => users.userId, { onDelete: 'cascade' }),

  /** Short summary (e.g. "Client dinner — Mumbai trip"). */
  title: varchar('title', { length: 255 }).notNull(),

  /** Detailed justification / supporting notes. */
  description: text('description').notNull(),

  /** Monetary value with 2-decimal precision (e.g. 12500.75). */
  amount: decimal('amount', { precision: 10, scale: 2 }).notNull(),

  /**
   * Overall request status.
   * Allowed values: 'PENDING' | 'APPROVED' | 'REJECTED'
   */
  status: varchar('status', { length: 20 }).notNull().default('PENDING'),

  /** Has the Reporting Manager approved? */
  rmApproved: boolean('rm_approved').notNull().default(false),

  /** Has the Accounts Payable Executive approved? */
  apeApproved: boolean('ape_approved').notNull().default(false),

  /** Has the CFO approved? */
  cfoApproved: boolean('cfo_approved').notNull().default(false),

  /** When the request was originally submitted. */
  createdAt: timestamp('created_at').defaultNow(),

  /** Last modification time — updated on every change. */
  updatedAt: timestamp('updated_at').defaultNow(),
});

// ─────────────────────────────────────────────────────────────────────────────
// TABLE 3: employeeAssignments
// ─────────────────────────────────────────────────────────────────────────────
// Maps each employee to exactly one Reporting Manager (RM).
// The UNIQUE constraint on employeeUserId enforces one-to-one:
//   one employee → one RM.  One RM can manage many employees.
// ─────────────────────────────────────────────────────────────────────────────
const employeeAssignments = pgTable('employee_assignments', {
  /** Internal PK. */
  id: serial('id').primaryKey(),

  /**
   * FK → users.user_id — the employee being assigned.
   * UNIQUE ensures each employee has exactly one RM.
   */
  employeeUserId: uuid('employee_user_id')
    .notNull()
    .unique()
    .references(() => users.userId, { onDelete: 'cascade' }),

  /**
   * FK → users.user_id — the reporting manager.
   * Not unique: one RM can manage many employees.
   */
  rmUserId: uuid('rm_user_id')
    .notNull()
    .references(() => users.userId, { onDelete: 'cascade' }),

  /** When the assignment was created. */
  createdAt: timestamp('created_at').defaultNow(),
});

module.exports = { users, reimbursements, employeeAssignments };
